# Generated by Django 3.2.7 on 2021-10-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
